config/routes.rb
Energie::Application.routes.draw do

  root :to => 'zips#index'
  post '/create' => 'zips#create'

end

app/models/zip.rb
# == Schema Information
#
# Table name: zips
#
#  id            :integer          not null, primary key
#  zip_code      :string(255)
#  lat           :float
#  long          :float
#  building_type :string(255)
#  kwh           :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Zip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zips_controller.rb
class ZipsController < ApplicationController

  def index
  end

  def create
    if Zip.blank?
      html = HTTParty.get('http://data.cityofnewyork.us/api/views/74cu-ncm4/rows.json')
      json = JSON(html.body)
      json['data'].each do |nrg|
        building_type = nrg[0][9]
        lat = nrg[0][8][1].to_f
        long = nrg[0][8][2].to_f
          if nrg[8][0].nil?
            zip_code = nil
          else
            zip_code = JSON(nrg[8][0])['zip']
          end
        kwh = nrg[0][10].to_f
        Zip.create[:zip_code => zip_code, :lat => lat, :long => long, :building_type => building_type, :kwh => kwh]
      end
    end
    redirect_to root_path
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Energie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zips/index.html.erb
<div id="show">
<%= button_to 'Show Energy Graph', create_path %>
</div><!-- #show -->

<div id="graph">
</div><!-- #graph -->

<div id="map">
</div><!-- #map -->